# spark configs
spark: 
  enable_hive: false
  spark_conf:
    spark.executor.memory: "4g"
    spark.driver.memory: "2g"
    spark.sql.shuffle.partitions: "200"

# logging configs 
logging:
  log_dir: "output/logs"
  log_file: "application.log"
  level: "INFO"
